# on : push
# jobs : 
#        first-job:
#          runs-on : ubuntu-latest
#          steps :
#                 - run: node --version
#                 - run: npm --version
#                 - uses : actions/checkout@v3
#                 - run : npx eslint index.js
#                 - run : node index.js


# CI CD PRINT NODE VERSION


# name: Print Node Version
# on: push
# jobs:
#   print-version:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Install Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14.x'
#       - name: Print Node Version
#         run: node -v



# CI CD ESLINT


name: Run ESLint
on:
  push:
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint index.js